#+title: Design

* Builtins and externals

** argparse

** sys

** mne

** numpy

*** typing

** scipy

*** linalg

- eigh

** sklearn

*** base

- BaseEstimator

- TransformerMixin

*** utils.validation

- check_is_fitted

** tmp

* [[file:~/personal/projects/42/total_perspective_vortex/mybci.py][mybci.py]]

An entrypoint of the project.

** =parse_args(argv)=

Is called from =main()=. Main purpose is to parse the given =argv=.

Creates an object =parser= (from module =argparse=). Defines arguments with validation and constraints (relative to subject, run, and mode). Parses according to outlined parser configuration (=parser.parse_args(argv)=). Goes through another validation step (checks non empty argument count, subject and run number ranges). Returns parsed arguments.

** =main(argv)=

Calles =parse_args(argv)=. Parsed arguments branch program to 3 paths:

- =args.subject == None=

  Calls =run_full_sweep()=.

- =args.mode == "train"=

  Calls =train(args.subject, runs_for(args.run))=.

- =args.mode == "predict"=

  Calls =predict(args.subject, runs_for(args.run))=.

* [[file:~/personal/projects/42/total_perspective_vortex/src/csp.py][csp.py]]

Heart of project. A from scratch implementation of CSP dimensionality reduction algorithm.

** =MyCSP(BaseEstimator, TransformerMixin)=

A class, inherits from =BaseExtimator= and =TransformerMixin=.


*** =__init__(n_components, log)=

Initialises self attributes from given arguments.

*** =_covariance(X)=

Gets the number of channels (=n_channels=). Reshapes the 3D tensor from =(epochs, channels, time)= to a 2D matrix of shape =(channels, epochs * time)= through tensor transposition and flattening. This concatenates the time-series of all epochs. Calculates covariance matrix (see "Concatenation estimator" from [[file:csp.org][csp.org]]).

Gets the number of channels (=n_channels=). Reshapes the 3D tensor from =(epochs, channels, time)= to a 2D matrix of shape =(channels, epochs * time)= through tensor transposition and flattening. This concatenates the time-series of all epochs. Calculates covariance matrix (see "Concatenation estimator" from [[file:csp.org][csp.org]]).

*** =fit(X, y)=

Validates =n_components= is even and =classes= count being exactly 2. Assigns =self.classes_=, and calculates covariance matrices for different classes (=S_0=, =S_1=). Calls =eigh(S_0, S_0 + S_1)= and obtains eigenvalues and eigenvectors: =eigvals=, =eigvecs= (see "Why =eigh= is the right solver" from [[file:csp.org][csp.org]]). Stores descendingly ordered eigenvalues and eigenvectors in =self.eigvals_= and =self.filters_= (=self.filters_= is sorted by columns eigenvector matrix). In parallel, stores pseudo-inverse of spatial filters (used in [[file:~/personal/projects/42/total_perspective_vortex/visualise.py][visualise.py]]).

Summing up, it calculates filter matrix which will be used to reduce dimensionality of raw epoch data. Its the main function of CSP.

*** =transform(X)=

Verifies the model is fitted using =check_is_fitted(self)= (which ensures the required learned attributes exist). Selects the leftmost and rightmost filters, as they produce the most discriminative variance between the two classes. Projects the raw data onto these selected filters (resulting in =X_prj=). Calculates the =features= array (of length =n_components=), where each value essentially represents the energy (variance) of the filtered brain activity. Finally, if =self.log= is set to =True=, a log transformation is applied to the features to compress extreme spikes and create a normal (bell-curve) distribution, which is much easier for linear classifiers to process. Returns features.
